# Generated by Django 3.2.8 on 2021-11-02 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0002_auto_20211102_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('req_url', models.TextField(default='', verbose_name='地址')),
                ('req_method', models.CharField(default='', max_length=100, verbose_name='方法')),
                ('req_header', models.TextField(default='', verbose_name='请求头')),
                ('req_ptype', models.CharField(default='', max_length=100, verbose_name='参数类型')),
                ('req_parameter', models.TextField(default='', verbose_name='参数')),
                ('res_assert', models.TextField(default='', verbose_name='验证')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.module')),
            ],
        ),
    ]
