# Generated by Django 3.2.8 on 2021-11-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0003_auto_20211108_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taskresult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='名称')),
                ('tests', models.IntegerField(default='', verbose_name='运行数')),
                ('failures', models.IntegerField(default='', verbose_name='失败数')),
                ('skipped', models.IntegerField(default='', verbose_name='跳过数')),
                ('errors', models.IntegerField(default='', verbose_name='错误数')),
                ('time', models.FloatField(default='', verbose_name='运行时长')),
                ('result', models.TextField(default='', verbose_name='结果描述')),
                ('run_time', models.DateTimeField(verbose_name='执行时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface_app.testtask')),
            ],
        ),
    ]
