# Generated by Django 3.2.8 on 2021-11-30 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0004_taskresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='task',
            new_name='task_id',
        ),
    ]
