# Generated by Django 3.2.8 on 2021-11-30 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0005_rename_task_taskresult_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskresult',
            old_name='task_id',
            new_name='task',
        ),
    ]
