# Generated by Django 3.2.8 on 2021-11-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='describe',
            field=models.TextField(default='', max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(default='', max_length=100, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.BooleanField(verbose_name='状态'),
        ),
    ]
