# Generated by Django 3.2.8 on 2021-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_auto_20211102_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='describe',
            field=models.TextField(default='', max_length=200, verbose_name='描述'),
        ),
    ]
