# Generated by Django 3.2.8 on 2021-12-03 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_project_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
    ]
